### ISSUE TITLE
WC 2.7 Compatibility 

### ISSUE THREAD

**Issue by bekarice** [skyverge/woocommerce-sequential-order-numbers#10]
- [x] **Misc** -- Drop support for WooCommerce < 2.5
   - ~~Replace any paid status checks with `$order->is_paid()`~~

- [x] **Misc** -- Add support for WooCommerce 2.7

   - [x] Add compat methods to get orders and favor accessors instead of directly using order properties

- [x] **Misc** -- Update tested up to / requires versions

- [x] **Misc** -- Update readme + changelog

- ~~**Investigate** -- Check this issue, if possible: https://github.com/skyverge/woocommerce-sequential-order-numbers/issues/11~~

**Comment by justinstern** [comment]
:dromedary_camel:
