### ISSUE TITLE
get_order_meta() arg 1 defined as WC_Order

### ISSUE THREAD

**Issue by decarvalhoaa** [skyverge/woocommerce-sequential-order-numbers#13]
Hello,

I'm using the **WooCommerce Sequential Order Numbers** latest version with **WooCommerce PDF Invoices & Packing Slips** and **WooCommerce PDF Invoices & Packing Slips Professional** versions 1.6.0 and 1.5.0 respectively, and I'm experience the following fatal error when I try to generate a Credit Note PDF:

`
[28-Mar-2017 10:44:03 UTC] PHP Catchable fatal error:  Argument 1 passed to WC_Seq_Order_Number::get_order_meta() must be an instance of WC_Order, instance of WC_Order_Refund given, called in /var/www/html/tlc-preprod/wp-content/plugins/woocommerce-sequential-order-numbers/woocommerce-sequential-order-numbers.php on line 232 and defined in /var/www/html/tlc-preprod/wp-content/plugins/woocommerce-sequential-order-numbers/woocommerce-sequential-order-numbers.php on line 440
`

In previous version of the WooCommerce PDF Invoices & Packing Slips, this issue can't be reproduced. However, IMHO I believe the issue is an oversight in your implementation. 

The method [get_order_meta()](https://github.com/skyverge/woocommerce-sequential-order-numbers/blob/master/woocommerce-sequential-order-numbers.php#L440) expect arg 1 to be an instance of WC_Order.
However, this arg is the second arg passed to the woocommerce_order_number filter. The filter is defined in WC_Abstract_Order class, and WC_Order and WC_Order_Refund both extend this class. IMO you could expect both instance types to be passed to the filter. Would you agree?

Thanks,
A

**Comment by unfulvio** [comment]
thanks @decarvalhoaa 

@bekarice https://github.com/skyverge/woocommerce-sequential-order-numbers/blob/c733a1b5143089d5f1a475997258427379d60910/woocommerce-sequential-order-numbers.php#L440

**Comment by bekarice** [comment]
@decarvalhoaa thanks for the heads up here, didn't realize refunds will also try to use core order number methods. Will remove the type-hinting on that method, which should resolve this, and deploy an update today.

**Comment by bekarice** [comment]
@decarvalhoaa WordPress.org deploys are broken at the moment, but you can download it from our GitHub release instead: https://github.com/skyverge/woocommerce-sequential-order-numbers/releases/download/1.8.1/woocommerce-sequential-order-numbers.1.8.1.zip

You'd deactivate, then delete the plugin, then upload this new version.

**Comment by decarvalhoaa** [comment]
Thanks @bekarice for the quick response and fix.

FYI, interestingly enough, the issue can only be reproduced in WC2.6.x. WC3.0 doesn't appear to suffer from this issue.
