### ISSUE TITLE
Compatibility FAQ

### ISSUE THREAD

**Issue by tamarazuk** [skyverge/woocommerce-sequential-order-numbers#2]
@bekarice Could we add an FAQ to the readme explaining why some extensions like gateways may not display the sequential order number? 

As usual, massage the below text to your heart's content :smiley_cat: . Thanks!

---

For full compatibility with extensions which alter the order number, such as Sequential Order Numbers, WooCommerce extensions should use `$order->get_order_number()` rather than `$order->id` when referencing the order number. If your extension is not displaying the correct order number, you can try contacting the developers of your payment gateway to see if it's possible to make this tiny change.

**Comment by bekarice** [comment]
![](https://media.giphy.com/media/HjPbLbmep2aJO/giphy.gif)
