### ISSUE TITLE
how to change number with persian number?

### ISSUE THREAD

**Issue by premier213** [skyverge/woocommerce-sequential-order-numbers#3]
hi,tnx for plugin !!

i want change start to persian number counter !
i have this problem!!
![2015-03-24_0-56-08](https://cloud.githubusercontent.com/assets/4321174/6789793/a5e16bb2-d1c0-11e4-8386-a0058e46fee1.png)

**Comment by tamarazuk** [comment]
Hi @premier213. Could you elaborate a bit on the problem you're having? Thanks!

**Comment by premier213** [comment]
tnx @tamarazuk 

when use {DD} or {MM} for prefix change number to persian number because use persian woocommerce but number for start for example : 200 not change to persian number !!

**Comment by premier213** [comment]
plz help me

**Comment by bekarice** [comment]
Hey @premier213 the lite version of the plugin (what this repo is for) does not accept prefixes. Is this for the [pro version](http://www.woothemes.com/products/sequential-order-numbers-pro/)? If so, can you please [submit a support request here](https://support.woothemes.com/hc/en-us/requests/new)? This repo is for the lite version only, but we'd be happy to get you sorted out via the WooThemes help desk. Thanks!
